stages:
  - build
  - test
  - release

variables:
  TESTING_IMAGE: $CI_REGISTRY_IMAGE:testing-$CI_COMMIT_SHA
  RELEASE_IMAGE: $CI_REGISTRY_IMAGE:dolfinx-proposal

build:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --pull -t $TESTING_IMAGE -f docker/Dockerfile .
    - docker push $TESTING_IMAGE

flake8_tutorials:
  image:
    name: $TESTING_IMAGE
  stage: test
  before_script:
    - export FENICS_CACHE_DIR=$CI_PROJECT_DIR/.fenics_cache
  script:
    - cd tutorials
    - pytest --flake8 -m flake8 -vv --html=pytest_flake8_tutorials.html --self-contained-html
  artifacts:
    paths:
      - tutorials/pytest_flake8_tutorials.html
    when: on_failure

flake8_tests:
  image:
    name: $TESTING_IMAGE
  stage: test
  before_script:
    - export FENICS_CACHE_DIR=$CI_PROJECT_DIR/.fenics_cache
  script:
    - cd $HOME/dolfinx/python/test/unit
    - pytest --flake8 -m flake8 -vv --html=pytest_flake8_tests.html --self-contained-html
  artifacts:
    paths:
      - $HOME/dolfinx/python/test/unit/pytest_flake8_tests.html
    when: on_failure

flake8_core:
  image:
    name: $TESTING_IMAGE
  stage: test
  before_script:
    - export FENICS_CACHE_DIR=$CI_PROJECT_DIR/.fenics_cache
  script:
    - cd /usr/local/lib/python3.7/dist-packages/dolfinx/
    - cp $HOME/dolfinx/python/setup.cfg .
    - pytest --flake8 -m flake8 -vv --html=pytest_flake8_core.html --self-contained-html
  artifacts:
    paths:
      - /usr/local/lib/python3.7/dist-packages/dolfinx/pytest_flake8_core.html
    when: on_failure

tutorials_serial:
  image:
    name: $TESTING_IMAGE
  stage: test
  before_script:
    - export FENICS_CACHE_DIR=$CI_PROJECT_DIR/.fenics_cache
  script:
    - cd tutorials
    - pytest -n auto -vv --html=pytest_tutorials_serial.html --self-contained-html
  artifacts:
    paths:
      - tutorials/pytest_tutorials_serial.html
    when: on_failure

tests_serial:
  image:
    name: $TESTING_IMAGE
  stage: test
  before_script:
    - export FENICS_CACHE_DIR=$CI_PROJECT_DIR/.fenics_cache
  script:
    - cd $HOME/dolfinx/python/test/unit
    - pytest -n auto -vv --html=pytest_tests_serial.html --self-contained-html
  artifacts:
    paths:
      - $HOME/dolfinx/python/test/unit/pytest_tests_serial.html
    when: on_failure

release:
  image: docker:latest
  services:
    - docker:dind
  stage: release
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $TESTING_IMAGE
    - docker tag $TESTING_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
  only:
    - fenicsx
